import Head from "next/head";
import Navbar from "../components/Navbar";
import Services from "../components/Services";

export default function ServicesPage() {
  return (
    <div className="services-page">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar />
      </header>

      <main>
        <Services />
      </main>
    </div>
  );
}
